### ISSUE TITLE
Container doesn't stretch to the bottom of the page.

### ISSUE THREAD

**Issue by Sigton** [SigtonShop/SigtonShop.github.io#5]
The title explains it all, really. I've tried loads of things but nothing has worked, height to auto, 100%, 100vh. Same problem.

Sigton

**Comment by joker314** [comment]
height at 100% will stretch it to its parent's size. Ensure you have done `html, body{ margin: 0px; padding: 0px;}` and then it is supposed to stretch to the bottom of what you can see. To exyend below, where you need to scroll, the height must be more than 100% iirc

**Comment by AwesomeMinecrafter94** [comment]
I am currently working on a fix.

**Comment by AwesomeMinecrafter94** [comment]
Fixed! All you needed to do is put the footer after the div class.

**Comment by Sigton** [comment]
Right thanks, whoops :P

Sigton
